import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title:"Privacy Policy — yHatePDF", description:"How yHatePDF processes supported PDF operations locally in your browser." };
const sections=[
  ["1. Our Privacy Principle","Your documents belong to you. Supported yHatePDF tools process the files you choose inside your browser. We do not upload those PDF contents to a yHatePDF document-processing server."],
  ["2. Files and Browser Memory","Files, page previews, and intermediate working data may remain in browser memory while a tool is open. Reloading or closing the page clears that working session. Downloaded output remains wherever your browser saves it."],
  ["3. Data We Do Not Need","You do not need an account to use the public tools. We do not add watermarks, sell document contents, use document text for advertising, or retain a cloud copy of files processed by supported local tools."],
  ["4. Basic Site Operations","Our hosting provider may process ordinary technical request information needed to deliver the website, such as IP address, browser type, timestamps, and security logs. That infrastructure data is separate from your locally processed PDF contents."],
  ["5. Local Storage","We use browser local storage for device-only preferences such as light or dark theme. The PDF Studio may store interface preferences locally, but does not place your source document into our server storage."],
  ["6. External Links","Links to iLoveMD, Buy Me a Coffee, Chrome Web Store, Product Hunt, Peerlist, and team profiles are governed by those services' own privacy practices. Opening them leaves yHatePDF."],
  ["7. Security and Limitations","Browser-local processing reduces file exposure, but no software can promise absolute security. Keep your browser updated, review sensitive documents before export, and avoid untrusted browser extensions with access to local files."],
  ["8. Contact and Changes","We may update this policy as the product changes. Material changes will be reflected on this page with a revised date. Questions can be raised through the public contact channels linked from our About page."],
];
export default function Privacy(){return <main className="legal-page page-container"><div className="section-rule"><span>— LEGAL / PRIVACY</span><Link href="/terms">TERMS & CONDITIONS ↗</Link></div><header className="legal-header"><div><span>LEGAL DOCUMENT</span><b>PRIVACY POLICY</b></div><h1>Your PDFs belong <em>to you.</em></h1><p>Last updated: September 21, 2026</p></header><div className="legal-layout"><aside><strong>THE SHORT VERSION</strong><p>Supported tools run in your browser. Your PDF content is not uploaded to our document-processing servers.</p><Link href="/#tools">EXPLORE LOCAL TOOLS ↗</Link></aside><article>{sections.map(([title,copy])=><section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</article></div></main>}
