"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronRight, Command, FileText, LoaderCircle, Moon, Plus, Search, ShieldCheck, Sun, Upload, X, Zap } from "lucide-react";
import { categories, tools, type Tool } from "@/lib/tool-registry";
import { extractText, imagesToPdf, mergePdfs, rotatePdf, splitPdf } from "@/lib/pdf-client";

type Theme = "light" | "dark";
const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export default function PdfWorkspace() {
  const [activeId, setActiveId] = useState("merge"); const [files, setFiles] = useState<File[]>([]); const [palette, setPalette] = useState(false); const [query, setQuery] = useState(""); const [theme, setTheme] = useState<Theme>("light"); const [range, setRange] = useState("1-1"); const [separatePages, setSeparatePages] = useState(false); const [rotation, setRotation] = useState(90); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const input = useRef<HTMLInputElement>(null);
  const active = tools.find((tool) => tool.id === activeId) ?? tools[0];
  const visibleTools = useMemo(() => tools.filter((tool) => `${tool.name} ${tool.description} ${tool.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query]);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPalette(true); } if (event.key === "Escape") setPalette(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  const choose = (tool: Tool) => { setActiveId(tool.id); setFiles([]); setNotice(null); setPalette(false); setQuery(""); };
  const addFiles = (picked: FileList | File[]) => { const next = Array.from(picked); const invalid = next.find((file) => active.id === "images-to-pdf" ? !["image/png", "image/jpeg"].includes(file.type) : !file.name.toLowerCase().endsWith(".pdf")); if (invalid) { setNotice(`${invalid.name} is not supported by ${active.name}.`); return; } setFiles(active.id === "merge" || active.id === "images-to-pdf" ? (current) => [...current, ...next] : [next[0]]); setNotice(null); };
  const run = async () => { if (!files.length) { setNotice("Choose a file first."); return; } if (active.status !== "ready") { setNotice(`${active.name} is being engineered locally and is not available yet. We won’t pretend otherwise.`); return; } setBusy(true); setNotice(null); try { if (active.id === "merge") await mergePdfs(files); if (active.id === "split") await splitPdf(files[0], range, separatePages); if (active.id === "rotate") await rotatePdf(files[0], rotation); if (active.id === "images-to-pdf") await imagesToPdf(files); if (active.id === "extract-text") { const count = await extractText(files[0]); setNotice(`Extracted text from ${count} page${count === 1 ? "" : "s"}. Your download is ready.`); } if (active.id !== "extract-text") setNotice("Done. Your file was processed on this device and downloaded."); localStorage.setItem("yhatepdf-last-action", active.name); } catch (error) { setNotice(error instanceof Error ? error.message : "That file could not be processed locally."); } finally { setBusy(false); } };
  const topTools = tools.filter((tool) => ["merge", "split", "compress", "studio", "protect"].includes(tool.id));

  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => choose(tools[0])} aria-label="yHatePDF home"><span className="brand-mark">y/</span><span>HATEPDF<span className="brand-dot">.online</span></span></button><nav aria-label="Main navigation"><button onClick={() => setPalette(true)}>All tools</button><button onClick={() => setPalette(true)}>PDF Studio <span className="soon">SOON</span></button><button onClick={() => setPalette(true)}>Privacy</button></nav><div className="top-actions"><button className="command-button" onClick={() => setPalette(true)}><Search size={16} /> Search tools <kbd>⌘ K</kbd></button><button className="icon-button" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Toggle color theme">{theme === "light" ? <Moon size={17} /> : <Sun size={17} />}</button></div></header>
    <section className="hero"><div className="eyebrow"><Zap size={13} fill="currentColor" /> ZERO UPLOADS. ZERO NONSENSE.</div><h1>PDFs were never<br />the problem.</h1><p>Bad PDF tools were. Do the work directly on your device — no account, no watermark, no wait.</p></section>
    <section className="workspace" aria-label="PDF workspace"><div className="tool-strip">{topTools.map((tool) => { const Icon = tool.icon; return <button key={tool.id} className={active.id === tool.id ? "tool-pill active" : "tool-pill"} onClick={() => choose(tool)}><Icon size={16} />{tool.name.replace(" PDF", "")}</button>; })}<button className="tool-pill more" onClick={() => setPalette(true)}><Plus size={16} /> More</button></div><div className="workspace-card"><div className={`tool-icon ${categories[active.category].color}`}><active.icon size={26} /></div><div className="workspace-heading"><div><span className="category-label">{categories[active.category].label}</span><h2>{active.name}</h2><p>{active.description}</p></div><span className={`status ${active.status}`}>{active.status === "ready" ? "READY" : "IN BUILD"}</span></div><div className="dropzone" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); addFiles(event.dataTransfer.files); }} onClick={() => input.current?.click()} role="button" tabIndex={0} onKeyDown={(event) => event.key === "Enter" && input.current?.click()}><input ref={input} type="file" className="sr-only" accept={active.accept} multiple={active.id === "merge" || active.id === "images-to-pdf"} onChange={(event) => event.target.files && addFiles(event.target.files)} /><div className="upload-icon"><Upload size={23} /></div><strong>Drop {active.id === "images-to-pdf" ? "images" : "a PDF"} here</strong><span>or click to browse · nothing leaves this browser</span></div>
      {files.length > 0 && <div className="selected-files"><div className="selected-heading"><span>{files.length} {files.length === 1 ? "file" : "files"} ready</span><button onClick={() => setFiles([])}>Clear all</button></div>{files.map((file, index) => <div className="file-row" key={`${file.name}-${index}`}><FileText size={20} /><div><strong>{file.name}</strong><span>{formatBytes(file.size)} · local only</span></div><button onClick={() => setFiles(current => current.filter((_, item) => item !== index))} aria-label={`Remove ${file.name}`}><X size={17} /></button></div>)}</div>}
      {active.id === "split" && <div className="options"><label>Pages to extract<input value={range} onChange={(event) => setRange(event.target.value)} placeholder="e.g. 1-3, 6" /></label><label className="checkbox-label"><input type="checkbox" checked={separatePages} onChange={(event) => setSeparatePages(event.target.checked)} /> Save every selected page in a ZIP</label></div>}
      {active.id === "rotate" && <div className="options compact"><span>Rotate every page</span>{[90, 180, 270].map((option) => <button key={option} onClick={() => setRotation(option)} className={rotation === option ? "option-choice selected" : "option-choice"}>{option}°</button>)}</div>}
      {notice && <div className="notice"><Check size={16} />{notice}</div>}<button className="run-button" onClick={run} disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <ChevronRight size={18} />} {busy ? "Processing locally…" : active.status === "ready" ? `${active.name} locally` : "See implementation status"}</button><div className="privacy-line"><ShieldCheck size={17} /><span>Your files are processed on this device. We don’t upload, retain, or inspect them.</span></div></div></section>
    <section className="tool-grid-section"><div className="section-heading"><div><span className="eyebrow">THE TOOL BELT</span><h2>Everything useful. Nothing shady.</h2></div><button onClick={() => setPalette(true)}>Browse all tools <ChevronRight size={16} /></button></div><div className="tool-grid">{tools.slice(0, 9).map((tool) => { const Icon = tool.icon; return <button key={tool.id} className="tool-card" onClick={() => choose(tool)}><span className={`card-icon ${categories[tool.category].color}`}><Icon size={21} /></span><span className="card-copy"><strong>{tool.name}</strong><small>{tool.description}</small></span><ChevronRight className="card-arrow" size={17} /></button>; })}</div></section>
    <footer><span>© 2026 yHatePDF.online</span><span><ShieldCheck size={14} /> Local-first by design</span><button onClick={() => setPalette(true)}>About the build</button></footer>
    {palette && <div className="palette-backdrop" onMouseDown={() => setPalette(false)}><section className="palette" role="dialog" aria-modal="true" aria-label="Search tools" onMouseDown={(event) => event.stopPropagation()}><div className="palette-search"><Search size={18} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try “smaller”, “password”, “combine”…" /><kbd>ESC</kbd></div><div className="palette-list"><p>TOOLS</p>{visibleTools.map((tool) => { const Icon = tool.icon; return <button key={tool.id} onClick={() => choose(tool)}><span className={`mini-icon ${categories[tool.category].color}`}><Icon size={17} /></span><span><strong>{tool.name}</strong><small>{tool.description}</small></span><em>{tool.status === "ready" ? "Ready" : "In build"}</em></button>})}</div><div className="palette-footer"><span><Command size={13} /> K to open anywhere</span><span>Files never leave your device</span></div></section></div>}
  </main>;
}
