"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Download, Eraser, ImagePlus, LoaderCircle, Maximize2, PenLine, Plus, RotateCcw, ShieldCheck, Trash2, Type, Upload, X } from "lucide-react";
import { appendPagePlan, createThumbnails, exportPlacedSignatures, renderFullPreview, type PagePlanItem, type PdfPageInfo, type PlacedSignature } from "@/lib/pdf-client";

type SourceMode = "type" | "draw" | "upload";
type ImageMode = "original" | "clean" | "black" | "blue";
type Gesture = { id: string; mode: "move" | "resize"; clientX: number; clientY: number; x: number; top: number; width: number } | null;
const pageKey=(item:Pick<PagePlanItem,"fileIndex"|"pageIndex">)=>`${item.fileIndex}:${item.pageIndex}`;
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));

function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("That signature image could not be read."));image.src=url;});}
async function processSignature(url:string,mode:ImageMode){
  const image=await loadImage(url);const scale=Math.min(1,1200/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("Image processing is unavailable in this browser.");context.drawImage(image,0,0,canvas.width,canvas.height);if(mode==="original")return canvas.toDataURL("image/png");const pixels=context.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const r=pixels.data[i],g=pixels.data[i+1],b=pixels.data[i+2];const lum=.299*r+.587*g+.114*b;const spread=Math.max(r,g,b)-Math.min(r,g,b);if(mode==="clean"){if(lum>238&&spread<30)pixels.data[i+3]=0;else{const contrast=clamp((lum-128)*1.28+128,0,255);pixels.data[i]=pixels.data[i]*.45+contrast*.55;pixels.data[i+1]=pixels.data[i+1]*.45+contrast*.55;pixels.data[i+2]=pixels.data[i+2]*.45+contrast*.55;}}else{pixels.data[i]=mode==="blue"?20:10;pixels.data[i+1]=mode==="blue"?53:10;pixels.data[i+2]=mode==="blue"?112:10;pixels.data[i+3]=clamp((245-lum)*2.2,0,255);}}context.putImageData(pixels,0,0);return canvas.toDataURL("image/png");
}
function typedSignature(text:string){const canvas=document.createElement("canvas");canvas.width=1000;canvas.height=260;const context=canvas.getContext("2d");if(!context)throw new Error("Signature rendering is unavailable.");context.clearRect(0,0,canvas.width,canvas.height);context.fillStyle="#17346f";context.font="italic 112px Georgia, serif";context.textBaseline="middle";context.fillText(text.trim(),26,132,940);return canvas.toDataURL("image/png");}

export default function SignatureStudio(){
  const [files,setFiles]=useState<File[]>([]);const [plan,setPlan]=useState<PagePlanItem[]>([]);const [thumbs,setThumbs]=useState<Record<string,PdfPageInfo>>({});const [active,setActive]=useState("");const [selected,setSelected]=useState<Set<string>>(new Set());const [fullPreview,setFullPreview]=useState("");const [sourceMode,setSourceMode]=useState<SourceMode>("type");const [imageMode,setImageMode]=useState<ImageMode>("clean");const [typed,setTyped]=useState("");const [drawn,setDrawn]=useState("");const [uploadVariants,setUploadVariants]=useState<Partial<Record<ImageMode,string>>>({});const [placements,setPlacements]=useState<PlacedSignature[]>([]);const [activePlacement,setActivePlacement]=useState("");const [scope,setScope]=useState<"active"|"selected"|"all">("active");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const pdfInput=useRef<HTMLInputElement>(null);const imageInput=useRef<HTMLInputElement>(null);const drawCanvas=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);const stage=useRef<HTMLDivElement>(null);const gesture=useRef<Gesture>(null);const activeItem=plan.find((item)=>item.id===active)??plan[0];const current=placements.find((item)=>item.id===activePlacement);
  useEffect(()=>{if(!activeItem||!files[activeItem.fileIndex])return;let alive=true;setFullPreview("");void renderFullPreview(files[activeItem.fileIndex],activeItem.pageIndex).then(url=>alive&&setFullPreview(url)).catch(cause=>alive&&setError(cause instanceof Error?cause.message:"Preview failed."));return()=>{alive=false};},[activeItem?.id,activeItem?.fileIndex,activeItem?.pageIndex,files]);
  async function addPdf(list:FileList){const incoming=Array.from(list);if(!incoming.length)return;setBusy(true);setError("");try{if(incoming.some(file=>!file.name.toLowerCase().endsWith(".pdf")&&file.type!=="application/pdf"))throw new Error("Choose PDF files only.");const first=files.length;const next=[...files,...incoming];const pages=await appendPagePlan(next,first);setFiles(next);setPlan(current=>[...current,...pages]);setSelected(current=>new Set([...current,...pages.map(item=>item.id)]));if(!active&&pages[0])setActive(pages[0].id);await createThumbnails(next,first,info=>setThumbs(current=>({...current,[`${info.fileIndex}:${info.pageIndex}`]:info})));setNotice(`${pages.length} page${pages.length===1?"":"s"} ready. Create a signature, then place it exactly where it belongs.`);}catch(cause){setError(cause instanceof Error?cause.message:"Could not open that PDF.");}finally{setBusy(false);if(pdfInput.current)pdfInput.current.value="";}}
  async function addImage(file:File){setBusy(true);setError("");try{const url=URL.createObjectURL(file);try{const entries=await Promise.all((["original","clean","black","blue"] as ImageMode[]).map(async mode=>[mode,await processSignature(url,mode)] as const));setUploadVariants(Object.fromEntries(entries));setSourceMode("upload");setImageMode("clean");setNotice("Four local signature treatments are ready. Pick the cleanest one before placement.");}finally{URL.revokeObjectURL(url);}}catch(cause){setError(cause instanceof Error?cause.message:"Could not prepare that signature image.");}finally{setBusy(false);if(imageInput.current)imageInput.current.value="";}}
  function point(event:ReactPointerEvent<HTMLCanvasElement>){const box=event.currentTarget.getBoundingClientRect();return{x:(event.clientX-box.left)*event.currentTarget.width/box.width,y:(event.clientY-box.top)*event.currentTarget.height/box.height};}
  function beginDraw(event:ReactPointerEvent<HTMLCanvasElement>){const context=event.currentTarget.getContext("2d");if(!context)return;drawing.current=true;event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);context.beginPath();context.moveTo(p.x,p.y);context.strokeStyle="#17346f";context.lineWidth=5;context.lineCap="round";context.lineJoin="round";}
  function moveDraw(event:ReactPointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const context=event.currentTarget.getContext("2d");if(!context)return;const p=point(event);context.lineTo(p.x,p.y);context.stroke();}
  function endDraw(event:ReactPointerEvent<HTMLCanvasElement>){drawing.current=false;setDrawn(event.currentTarget.toDataURL("image/png"));}
  function signatureAsset(){if(sourceMode==="type"){if(!typed.trim())throw new Error("Type your signature first.");return{image:typedSignature(typed),label:`Typed: ${typed.trim()}`};}if(sourceMode==="draw"){if(!drawn)throw new Error("Draw your signature first.");return{image:drawn,label:"Drawn signature"};}const image=uploadVariants[imageMode];if(!image)throw new Error("Upload a signature image first.");return{image,label:`Imported · ${imageMode}`};}
  function place(){try{const asset=signatureAsset();const targets=scope==="all"?plan.map(item=>item.id):scope==="selected"?[...selected]:activeItem?[activeItem.id]:[];if(!targets.length)throw new Error("Choose at least one page.");const additions=targets.map((pageId,index):PlacedSignature=>({id:crypto.randomUUID(),pageId,image:asset.image,label:asset.label,x:62,top:72,width:26,rotation:0,opacity:1}));setPlacements(current=>[...current,...additions]);if(additions[0])setActivePlacement(additions[0].id);setNotice(`Signature placed on ${additions.length} page${additions.length===1?"":"s"}. Drag it on the document and use the corner handle to resize.`);setError("");}catch(cause){setError(cause instanceof Error?cause.message:"Could not place the signature.");}}
  function update(id:string,patch:Partial<PlacedSignature>){setPlacements(current=>current.map(item=>item.id===id?{...item,...patch}:item));}
  function beginGesture(event:ReactPointerEvent,id:string,mode:"move"|"resize"){const item=placements.find(entry=>entry.id===id);if(!item)return;event.currentTarget.setPointerCapture(event.pointerId);event.stopPropagation();gesture.current={id,mode,clientX:event.clientX,clientY:event.clientY,x:item.x,top:item.top,width:item.width};setActivePlacement(id);}
  function moveGesture(event:ReactPointerEvent){const value=gesture.current;const box=stage.current?.getBoundingClientRect();if(!value||!box)return;event.stopPropagation();if(value.mode==="move")update(value.id,{x:clamp(value.x+(event.clientX-value.clientX)/box.width*100,0,94),top:clamp(value.top+(event.clientY-value.clientY)/box.height*100,0,94)});else update(value.id,{width:clamp(value.width+(event.clientX-value.clientX)/box.width*100,5,80)});}
  async function exportPdf(){setBusy(true);setError("");try{await exportPlacedSignatures(files,plan,placements);setNotice("Your precisely placed signatures are exported. The original PDF remains unchanged.");}catch(cause){setError(cause instanceof Error?cause.message:"Signature export failed.");}finally{setBusy(false);}}
  const pagePlacements=placements.filter(item=>item.pageId===activeItem?.id);
  return <main className="signature-studio page-container"><div className="section-rule"><span>— EDIT / SIGN PDF</span><Link href="/#tools"><ArrowLeft/> ALL TOOLS</Link></div><header className="studio-heading"><div><p className="eyebrow">TYPE. DRAW. IMPORT. CLEAN. PLACE.</p><h1>Sign with <em>control.</em></h1><p>Build a reusable-looking signature, then drag, resize, rotate, and place it on any page—not just a preset corner.</p></div><span><ShieldCheck/> LOCAL WORKSPACE</span></header>
    <input ref={pdfInput} className="sr-only" type="file" accept=".pdf,application/pdf" multiple onChange={event=>event.target.files&&void addPdf(event.target.files)}/><input ref={imageInput} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>event.target.files?.[0]&&void addImage(event.target.files[0])}/>
    {!files.length?<section className="studio-empty" role="button" tabIndex={0} onClick={()=>pdfInput.current?.click()} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")pdfInput.current?.click()}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void addPdf(event.dataTransfer.files)}}><Upload/><h2>Drop the PDF you need to sign</h2><p>The document never leaves this browser.</p><span>PDF FILE · NO ACCOUNT · NO WATERMARK</span></section>:<section className="signature-shell">
      <aside className="signature-pages"><div className="studio-pane-title"><div><strong>PAGES</strong><span>{plan.length} TOTAL</span></div><button onClick={()=>pdfInput.current?.click()}><Plus/> ADD PDF</button></div><div className="signature-page-list">{plan.map((item,index)=>{const info=thumbs[pageKey(item)];const count=placements.filter(mark=>mark.pageId===item.id).length;return <article key={item.id} className={`${activeItem?.id===item.id?"active":""} ${selected.has(item.id)?"selected":""}`}><label><input type="checkbox" checked={selected.has(item.id)} onChange={()=>setSelected(current=>{const next=new Set(current);next.has(item.id)?next.delete(item.id):next.add(item.id);return next})}/><span>{index+1}</span><b>{count||""}</b></label><button onClick={()=>setActive(item.id)}>{info?<img src={info.thumbnail} alt={`Page ${index+1}`}/>:<LoaderCircle className="spin"/>}</button><small>{files[item.fileIndex]?.name} · p.{item.pageIndex+1}</small></article>})}</div></aside>
      <section className="signature-canvas"><div className="signature-canvas-bar"><span>PAGE {Math.max(1,plan.findIndex(item=>item.id===activeItem?.id)+1)} / {plan.length}</span><span>{pagePlacements.length} SIGNATURE{pagePlacements.length===1?"":"S"}</span></div><div className="signature-stage" ref={stage} onPointerMove={moveGesture} onPointerUp={()=>gesture.current=null} onPointerCancel={()=>gesture.current=null}>{fullPreview?<div className="signature-document"><img src={fullPreview} alt="PDF page preview"/>{pagePlacements.map(item=><div key={item.id} className={`placed-signature ${activePlacement===item.id?"active":""}`} style={{left:`${item.x}%`,top:`${item.top}%`,width:`${item.width}%`,transform:`rotate(${item.rotation}deg)`,opacity:item.opacity}} onPointerDown={event=>beginGesture(event,item.id,"move")}><img src={item.image} alt={item.label}/>{activePlacement===item.id&&<button className="signature-resize" aria-label="Resize signature" onPointerDown={event=>beginGesture(event,item.id,"resize")}><Maximize2/></button>}</div>)}</div>:<LoaderCircle className="spin"/>}</div>{current&&<div className="placement-controls"><label>WIDTH <input type="range" min="5" max="80" value={current.width} onChange={event=>update(current.id,{width:Number(event.target.value)})}/><b>{Math.round(current.width)}%</b></label><label>ROTATION <input type="range" min="-45" max="45" value={current.rotation} onChange={event=>update(current.id,{rotation:Number(event.target.value)})}/><b>{current.rotation}°</b></label><label>OPACITY <input type="range" min="0.25" max="1" step="0.05" value={current.opacity} onChange={event=>update(current.id,{opacity:Number(event.target.value)})}/><b>{Math.round(current.opacity*100)}%</b></label><button onClick={()=>{setPlacements(items=>items.filter(item=>item.id!==current.id));setActivePlacement("")}}><Trash2/> REMOVE</button></div>}</section>
      <aside className="signature-maker"><div className="studio-pane-title"><div><strong>SIGNATURE LAB</strong><span>CREATE + PLACE</span></div></div><div className="signature-source-tabs">{([['type',Type,'TYPE'],['draw',PenLine,'DRAW'],['upload',ImagePlus,'IMAGE']] as const).map(([mode,Icon,label])=><button key={mode} className={sourceMode===mode?"active":""} onClick={()=>setSourceMode(mode)}><Icon/>{label}</button>)}</div>{sourceMode==="type"&&<div className="signature-source-panel"><label>YOUR SIGNATURE<input value={typed} onChange={event=>setTyped(event.target.value)} placeholder="Sahaj Chawla"/></label><div className="typed-preview">{typed||"Your name"}</div><p>Rendered locally as an italic signature. Nothing is stored.</p></div>}{sourceMode==="draw"&&<div className="signature-source-panel"><canvas ref={drawCanvas} width="720" height="240" onPointerDown={beginDraw} onPointerMove={moveDraw} onPointerUp={endDraw} onPointerCancel={endDraw}/><button className="maker-subtle" onClick={()=>{drawCanvas.current?.getContext("2d")?.clearRect(0,0,720,240);setDrawn("")}}><Eraser/> CLEAR AND REDRAW</button><p>Use a mouse, trackpad, stylus, or finger.</p></div>}{sourceMode==="upload"&&<div className="signature-source-panel"><button className="image-upload" onClick={()=>imageInput.current?.click()}><ImagePlus/> IMPORT SIGNATURE IMAGE</button>{Object.keys(uploadVariants).length>0&&<div className="signature-variants">{(["original","clean","black","blue"] as ImageMode[]).map(mode=><button key={mode} className={imageMode===mode?"active":""} onClick={()=>setImageMode(mode)}><span>{uploadVariants[mode]&&<img src={uploadVariants[mode]} alt={`${mode} signature treatment`}/>}</span><b>{mode==="original"?"ORIGINAL":mode==="clean"?"REMOVE BG":mode==="black"?"SCAN / BLACK":"BLUE INK"}</b></button>)}</div>}<p>All four treatments are generated on your device. Pick the one that looks most natural.</p></div>}<div className="signature-placement-panel"><label>PLACE ON<select value={scope} onChange={event=>setScope(event.target.value as typeof scope)}><option value="active">Current page only</option><option value="selected">Selected pages ({selected.size})</option><option value="all">Every page ({plan.length})</option></select></label><button className="queue-button" onClick={place}><Plus/> PLACE SIGNATURE</button></div><div className="certificate-note"><strong><ShieldCheck/> VISIBLE VS DIGITAL SIGNING</strong><p>This tool adds a visible signature. Certificate/DSC signing is cryptographic and needs a valid certificate plus a trusted signing bridge or token driver. We keep these separate so a visual mark is never misrepresented as a legally verifiable digital signature.</p></div></aside>
      <div className="studio-export">{error&&<div className="feedback error"><X/>{error}</div>}{notice&&<div className="feedback success"><Check/>{notice}</div>}<button onClick={()=>void exportPdf()} disabled={busy||!placements.length}>{busy?<LoaderCircle className="spin"/>:<Download/>} {busy?"BUILDING SIGNED PDF…":`EXPORT SIGNED PDF · ${placements.length} PLACEMENT${placements.length===1?"":"S"}`}</button><p><ShieldCheck/> The original stays untouched. Review every placement before export.</p></div>
    </section>}
  </main>;
}
