import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title:"Terms & Conditions", description:"Terms for using yHatePDF's local-first PDF tools and Chrome extension.", alternates: { canonical: "/terms" } };
const sections=[
  ["1. Acceptance","By using yHatePDF.online, its downloadable extension kit, or its browser-based tools, you agree to these terms. If you do not agree, do not use the service."],
  ["2. Permitted Use","You may use yHatePDF for lawful personal, academic, and commercial document tasks. You may not use the service to violate rights, bypass access controls, distribute malware, attack the website, or process material you are not authorized to handle."],
  ["3. Your Documents","You retain ownership and responsibility for your files and outputs. You are responsible for checking page order, text, signatures, redactions, conversions, and other changes before relying on or distributing an exported file."],
  ["4. Electronic Signatures","The current signing tools place a visible signature mark. They do not issue a cryptographic certificate or independently verify identity. Whether a visible or electronic signature is legally sufficient depends on your jurisdiction and use case."],
  ["5. No Professional Advice","yHatePDF is a document utility, not legal, tax, medical, compliance, accessibility, archival, or security advice. For regulated or high-stakes documents, obtain appropriate professional review."],
  ["6. Availability and Warranties","The service is provided “as is” and “as available.” We do not guarantee uninterrupted availability, perfect conversion fidelity, recovery of damaged files, or compatibility with every PDF feature, font, form, signature, encryption method, or browser."],
  ["7. Limitation of Liability","To the maximum extent allowed by law, yHatePDF and its contributors are not liable for indirect, incidental, special, consequential, or data-loss damages arising from use of the service. Always keep an original copy before editing."],
  ["8. Extension Distribution","The developer ZIP is supplied for transparent, manual installation and Chrome Web Store submission preparation. Review its permissions before loading it. Direct consumer installation is available only through an approved Chrome Web Store listing once published."],
  ["9. Changes and Termination","We may improve, change, suspend, or retire features and may update these terms. Continued use after an update means you accept the revised terms."],
  ["10. Project Operator","yHatePDF is an independent companion project to iLoveMD, built and maintained by the same team. Project and support links are available on the About page."],
];
export default function Terms(){return <main className="legal-page page-container"><div className="section-rule"><span>— LEGAL / TERMS</span><Link href="/privacy">PRIVACY POLICY ↗</Link></div><header className="legal-header"><div><span>LEGAL DOCUMENT</span><b>TERMS & CONDITIONS</b></div><h1>Clear terms for <em>practical tools.</em></h1><p>Last updated: September 21, 2026</p></header><div className="legal-layout"><aside><strong>BEFORE YOU EXPORT</strong><p>Keep the original, inspect the result, and use qualified review for regulated or high-stakes documents.</p><Link href="/about">ABOUT THE PROJECT ↗</Link></aside><article>{sections.map(([title,copy])=><section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</article></div></main>}
