"use client";

const download = (blob: Blob, filename: string) => { const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(href), 1_000); };
const outputName = (name: string, suffix: string, extension = "pdf") => `${name.replace(/\.pdf$/i, "")}-${suffix}.${extension}`;

export async function mergePdfs(files: File[]) { const { PDFDocument } = await import("pdf-lib"); const output = await PDFDocument.create(); for (const file of files) { const source = await PDFDocument.load(await file.arrayBuffer()); const pages = await output.copyPages(source, source.getPageIndices()); pages.forEach((page) => output.addPage(page)); } download(new Blob([await output.save()], { type: "application/pdf" }), "merged.pdf"); }
function parseRanges(input: string, max: number) { const values = new Set<number>(); for (const group of input.split(",").map((part) => part.trim()).filter(Boolean)) { const [first, last = first] = group.split("-").map((value) => Number(value.trim())); if (!Number.isInteger(first) || !Number.isInteger(last) || first < 1 || last < first || last > max) throw new Error(`Use page numbers between 1 and ${max}; for example 1-3, 6.`); for (let page = first; page <= last; page += 1) values.add(page - 1); } if (!values.size) throw new Error("Choose at least one page."); return [...values].sort((a, b) => a - b); }
export async function splitPdf(file: File, ranges: string, separatePages: boolean) { const { PDFDocument } = await import("pdf-lib"); const source = await PDFDocument.load(await file.arrayBuffer()); const selected = parseRanges(ranges, source.getPageCount()); if (!separatePages) { const output = await PDFDocument.create(); (await output.copyPages(source, selected)).forEach((page) => output.addPage(page)); download(new Blob([await output.save()], { type: "application/pdf" }), outputName(file.name, "pages")); return; } const JSZip = (await import("jszip")).default; const archive = new JSZip(); for (const index of selected) { const output = await PDFDocument.create(); output.addPage((await output.copyPages(source, [index]))[0]); archive.file(outputName(file.name, `page-${index + 1}`), await output.save()); } download(await archive.generateAsync({ type: "blob" }), outputName(file.name, "split", "zip")); }
export async function rotatePdf(file: File, degrees: number) { const { PDFDocument, degrees: toDegrees } = await import("pdf-lib"); const pdf = await PDFDocument.load(await file.arrayBuffer()); pdf.getPages().forEach((page) => page.setRotation(toDegrees((page.getRotation().angle + degrees) % 360))); download(new Blob([await pdf.save()], { type: "application/pdf" }), outputName(file.name, "rotated")); }
export async function imagesToPdf(files: File[]) { const { PDFDocument } = await import("pdf-lib"); const pdf = await PDFDocument.create(); for (const file of files) { const bytes = await file.arrayBuffer(); const image = file.type === "image/png" ? await pdf.embedPng(bytes) : await pdf.embedJpg(bytes); const page = pdf.addPage([image.width, image.height]); page.drawImage(image, { x: 0, y: 0, width: image.width, height: image.height }); } download(new Blob([await pdf.save()], { type: "application/pdf" }), "images.pdf"); }
export async function extractText(file: File) { const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); const task = pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()), disableWorker: true }); const document = await task.promise; const pages: string[] = []; for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) { const page = await document.getPage(pageNumber); const text = await page.getTextContent(); pages.push(text.items.map((item) => ("str" in item ? item.str : "")).join(" ")); } download(new Blob([pages.join("\n\n\f\n\n")], { type: "text/plain;charset=utf-8" }), outputName(file.name, "text", "txt")); return document.numPages; }
