import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, Command, Download, FileStack, Globe2, Keyboard, ShieldCheck, Sparkles } from "lucide-react";
import BrandMark from "@/components/BrandMark";

export const metadata: Metadata = { title:"Chrome Extension — yHatePDF", description:"Install the yHatePDF quick-tools launcher for Chrome or download the Manifest V3 upload kit." };

const tools=[["MERGE PDF","Combine files and mix pages."],["SPLIT PDF","Choose ranges or individual pages."],["PDF STUDIO","Run multiple edits in one session."],["COMPRESS PDF","Optimize a file locally."],["SIGN PDF","Add a visible typed or drawn signature."],["ORGANIZE","Reorder, rotate, duplicate, or remove pages."]];

export default function ExtensionPage(){return <main className="extension-page page-container">
  <Link className="back-link" href="/"><ArrowLeft/> BACK TO HOME</Link>
  <section className="extension-hero">
    <div className="extension-status"><span><Check/> MANIFEST V3 KIT READY</span><b>CHROME WEB STORE · PENDING LISTING</b></div>
    <div className="extension-hero-grid"><div><p className="eyebrow">THE PDF TOOLBOX IN YOUR TOOLBAR.</p><h1>yHatePDF <em>Chrome Extension.</em></h1><p>Open the right PDF workspace without hunting through tabs. The extension is a fast, private launcher for Merge, Split, Compress, Sign, Organize, and the full PDF Studio.</p><div className="extension-actions"><span className="button button-muted" aria-disabled="true"><Globe2/> CHROME WEB STORE — COMING SOON</span><a className="button button-dark" href="/downloads/yhatepdf-chrome-extension-v1.0.0.zip" download><Download/> DOWNLOAD UPLOAD KIT</a></div><small>The ZIP is ready for Chrome&apos;s “Load unpacked” flow and Chrome Web Store dashboard upload.</small></div>
      <div className="extension-mock"><div className="mock-top"><BrandMark/><span>QUICK TOOLS</span></div><div className="mock-grid">{tools.map(([name,copy],i)=><div key={name}><span>0{i+1}</span><strong>{name}</strong><p>{copy}</p></div>)}</div><div className="mock-footer"><ShieldCheck/> No file permissions. Opens yHatePDF tools in a new tab.</div></div>
    </div>
  </section>
  <section className="extension-spec"><div className="section-rule"><span>— EXTENSION MINI-APP SPECIFICATION</span><span>VERSION 1.0.0</span></div><div className="extension-feature-grid"><article><ShieldCheck/><strong>MINIMAL PERMISSIONS</strong><p>Only context-menu and storage permissions. No history, downloads, file-system, or all-sites access.</p></article><article><Keyboard/><strong>ONE SHORTCUT</strong><p>Press Alt/Option + Shift + Y to open PDF Studio from any Chrome tab.</p></article><article><FileStack/><strong>QUICK TOOL ROUTING</strong><p>Every action opens its dedicated, bookmarkable workspace instead of a cramped conversion popup.</p></article><article><Sparkles/><strong>WEBSITE-MATCHED UI</strong><p>The popup shares the same monochrome grid, typography, and direct navigation as yHatePDF.</p></article></div></section>
  <section className="install-guide"><div className="section-rule"><span>— 3-STEP QUICK INSTALLATION</span><span>DEVELOPER / TEST MODE</span></div><div className="install-grid"><article><b>01</b><h2>Download & unzip</h2><p>Download the upload kit above and extract <code>yhatepdf-chrome-extension-v1.0.0.zip</code> into a folder.</p></article><article><b>02</b><h2>Enable Developer mode</h2><p>Open <code>chrome://extensions</code> in Chrome, then switch on Developer mode in the upper-right corner.</p></article><article><b>03</b><h2>Load unpacked</h2><p>Select “Load unpacked” and choose the extracted folder containing <code>manifest.json</code>. Pin yHatePDF to the toolbar.</p></article></div></section>
  <section className="store-kit"><div><Command/><span>STORE SUBMISSION KIT</span><h2>Built to upload,<br/><em>ready to list.</em></h2><p>The downloadable ZIP keeps <code>manifest.json</code> at the archive root, includes 16/48/128px icons, uses a Manifest V3 service worker, and contains no remotely hosted code.</p></div><div className="store-checklist"><strong>PACKAGE CHECKLIST</strong>{["Manifest V3","Toolbar popup","Keyboard command","Context-menu launcher","Privacy-first permissions","Store-ready ZIP root"].map(item=><span key={item}><Check/> {item}</span>)}<a className="button button-dark" href="/downloads/yhatepdf-chrome-extension-v1.0.0.zip" download>DOWNLOAD VERSION 1.0.0 <ArrowUpRight/></a></div></section>
</main>}
